---
deployment:
  tasks:
    - /bin/mkdir -p /home/isandybe/public_html/werkuren
    - cp /home/isandybe/public_html/werkuren/db.php /home/isandybe/public_html/werkuren/db_live.php || true
    - /bin/cp -R dist/* /home/isandybe/public_html/werkuren/
    - cp /home/isandybe/public_html/werkuren/db_live.php /home/isandybe/public_html/werkuren/db.php || true
    - rm -f /home/isandybe/public_html/werkuren/db_live.php
